apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"

  - name: ClickHouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: sigmax
    basicAuth: false
    editable: true
    jsonData:
      defaultDatabase: sigmax
      timeout: 10

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: sigmax
    user: sigmax
    editable: true
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
    secureJsonData:
      password: "sigmax"
